package bookapp;
// Generated Mar 16, 2017 6:59:13 AM by Hibernate Tools 4.3.1



/**
 * Title generated by hbm2java
 */
public class Title  implements java.io.Serializable {


     private Integer id;
     private int titleId;
     private String title;

    public Title() {
    }

    public Title(int titleId, String title) {
       this.titleId = titleId;
       this.title = title;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getTitleId() {
        return this.titleId;
    }
    
    public void setTitleId(int titleId) {
        this.titleId = titleId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


