package doggie;
// Generated Mar 11, 2017 9:34:41 AM by Hibernate Tools 4.3.1

import java.util.Iterator;




/**
 * Dogs generated by hbm2java
 */
public class Dogs  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String breed;
     private String age;

    public Dogs() {
    }

    public Dogs(String name, String breed, String age) {
       this.name = name;
       this.breed = breed;
       this.age = age;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getBreed() {
        return this.breed;
    }
    
    public void setBreed(String breed) {
        this.breed = breed;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }

    
   



}


