package book_app;
// Generated Mar 24, 2017 9:51:53 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Books generated by hbm2java
 */
public class Books  implements java.io.Serializable {


     private Integer id;
     private String callno;
     private String name;
     private String author;
     private String publisher;
     private int quantity;
     private int issued;
     private Date addedDate;
     private String genre;

    public Books() {
    }

	
    public Books(String callno, String name, String author, String publisher, int quantity, int issued, Date addedDate) {
        this.callno = callno;
        this.name = name;
        this.author = author;
        this.publisher = publisher;
        this.quantity = quantity;
        this.issued = issued;
        this.addedDate = addedDate;
    }
    public Books(String callno, String name, String author, String publisher, int quantity, int issued, Date addedDate, String genre) {
       this.callno = callno;
       this.name = name;
       this.author = author;
       this.publisher = publisher;
       this.quantity = quantity;
       this.issued = issued;
       this.addedDate = addedDate;
       this.genre = genre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCallno() {
        return this.callno;
    }
    
    public void setCallno(String callno) {
        this.callno = callno;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getIssued() {
        return this.issued;
    }
    
    public void setIssued(int issued) {
        this.issued = issued;
    }
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }




}


