package book_app;
// Generated Mar 24, 2017 9:51:53 AM by Hibernate Tools 4.3.1



/**
 * Librarian generated by hbm2java
 */
public class Librarian  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String password;
     private String email;
     private String address;
     private String city;
     private String contact;

    public Librarian() {
    }

    public Librarian(String name, String password, String email, String address, String city, String contact) {
       this.name = name;
       this.password = password;
       this.email = email;
       this.address = address;
       this.city = city;
       this.contact = contact;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }




}


